
apiVersion: apimanagement.gloo.solo.io/v2
kind: ApiDoc
metadata:
  name: products-sdl
  namespace: bookinfo
spec:
  graphql:
    schemaDefinition: |-
      type Query {
        """Description of a book in HTML"""
        products: [Product] 
      }
      """Each book has a product entry"""
      type Product {
        """Unique identifier for books"""
      id: String
      """The book title"""
      title: String
      """Description of a book in HTML"""
      descriptionHtml: String
      }