
apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLResolverMap
metadata:
  name: products-resolvers
  namespace: bookinfo
spec:
  types:
    Query:
      fields:
        products:
          resolvers:
          - restResolver:
              destinations:
              - port:
                  number: 9080
                ref:
                  name: productpage
                  namespace: bookinfo
              request:
                headers:
                  :path:
                    jq: '"/api/v1/products"'